repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/doublify/pre-commit-clang-format
    sha: master
    hooks:
      - id: clang-format

  - repo: https://github.com/ambv/black
    sha: master
    hooks:
      - id: black

  - repo: git://github.com/doublify/pre-commit-isort
    sha: master
    hooks:
      - id: isort
